version: '3'
services:
  db:
    image: mysql:8.0.31
    container_name: taskdb
    ports: 
      - "3307:3306"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DB=myproject
      - MYSQL_USER=psh
      - MYSQL_PASSWORD=psh
      - TZ=Asia/Seoul
  web:
    image: django:5.0.4
    container_name: Task
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db